title: Introduction to R and RStudio
remote_theme: ubc-library-rc/rc-workshop-template
footer_content: "<a href=\"https://github.com/ubc-library-rc/r-rstudio/\">View in GitHub</a>"
search_enabled: false
